name = "FREEDOMojis"
type = "webpack"
route = ''
zone_id = 'cecc62c6f9eda53a65ff90b92c0c6858'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-10-07"
